whi_modbus_io:
  ros__parameters:
    init_levels: /home/nvidia/ros2_ws/src/whi_modbus_io/config/init_levels.yaml
    hardware_interface:
      module: DAQM-43xx
      device_addr: 0x07
      modbus_instance: server_depend
      server_depend:
        modbus_service: modbus_request
      stand_alone:
        port: /dev/ttyUART_485_1
        baudrate: 115200
    debug:
      print_comm: false
