whi_modbus_io:
  ros__parameters:
    service: io_request
    init_levels: /home/nvidia/ros2_ws/src/whi_modbus_io/config/init_levels.yaml
    hardware_interface:
      module: DAQM-43xx
      port: /dev/ttyUART_485_2
      baudrate: 9600

